### ISSUE TITLE
試跑聲學模型 dockerfile討論

### ISSUE THREAD

**Issue by leo424y** [twgo/siann1-hak8_boo5-hing5#4]
回報jenkins執行結果

**Comment by leo424y** [comment]
http://172.16.3.135/job/siann1-hak8_boo5-hing5/18/console
噴
```
Step 33/44 : RUN python3 manage.py 匯入台文語料庫2版 /usr/local/gi2_liau7_khoo3/twisas2.json

 ---> Running in 0e028f55ab93

[91m綜合標音deprecated，0.7版會提掉
綜合標音deprecated，0.7版會提掉
綜合標音deprecated，0.7版會提掉
[0m
資料數量：0
檢查格式了匯入

[91mTraceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/dist-packages/匯入到臺灣言語資料庫/management/commands/匯入台文語料庫2版.py", line 43, in handle
    訓練過渡格式.加一堆資料(全部資料)
  File "/usr/local/lib/python3.5/dist-packages/臺灣言語服務/models.py", line 46, in 加一堆資料
    一筆.full_clean()
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 1235, in full_clean
    self.clean()
  File "/usr/local/lib/python3.5/dist-packages/臺灣言語服務/models.py", line 65, in clean
    檢查聽拍結束時間有超過音檔無(self.聲音檔().時間長度(), self.聽拍)
  File "/usr/local/lib/python3.5/dist-packages/臺灣言語服務/models.py", line 57, in 聲音檔
    return 聲音檔.對檔案讀(self.影音所在)
  File "/usr/local/lib/python3.5/dist-packages/臺灣言語工具/語音辨識/聲音檔.py", line 11, in 對檔案讀
    with wave.open(音檔所在, 'rb') as wave音檔:
  File "/usr/lib/python3.5/wave.py", line 499, in open
    return Wave_read(f)
  File "/usr/lib/python3.5/wave.py", line 163, in __init__
    self.initfp(f)
  File "/usr/lib/python3.5/wave.py", line 130, in initfp
    raise Error('file does not start with RIFF id')
wave.Error: file does not start with RIFF id
```
@sih4sing5hong5 
這是'twisas'只傳'MH'試跑的結果，會是語料還沒傳完的關係？

**Comment by leo424y** [comment]
已使用完整twsas語料，仍產生一樣error  
`wave.Error: file does not start with RIFF id`

**Comment by sih4sing5hong5** [comment]
進前copy的cache敢有清掉？

**Comment by leo424y** [comment]
我在dockerfile最前面放這個
ARG CACHEBUST=1

等同下 docker build ... --no-cache 之後

結果一樣

**Comment by sih4sing5hong5** [comment]
`find + md5sum`
`find + file`
的結果分別是啥？

**Comment by leo424y** [comment]
解了！
裝 ffmpeg 就過了
http://blog.csdn.net/appleyuchi/article/details/78486179

**Comment by leo424y** [comment]
解決問題了，原來是沒裝lfs 好糗！ 已跑到到 走評估.sh 待回報結果

```
# 掠語料
# download twisas
WORKDIR /usr/local/
RUN apt-get install curl
RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
RUN apt-get install git-lfs
RUN git lfs install
RUN git lfs clone -b 0222a http://lfs:lfs@172.16.3.136/twisas.git
```

**Comment by leo424y** [comment]
最後一步跑滿久的超過一小時...
```
Step 48/49 : RUN bash -c 'time bash -x 走評估.sh data/lang_free'

 ---> Running in cd06d3045332

[91m+ . cmd.sh
++ export train_cmd=run.pl
++ train_cmd=run.pl
++ export 'decode_cmd=run.pl --mem 4G'
++ decode_cmd='run.pl --mem 4G'
++ export 'mkgraph_cmd=run.pl --mem 8G'
++ mkgraph_cmd='run.pl --mem 8G'
++ export 'cuda_cmd=run.pl --gpu 1'
++ cuda_cmd='run.pl --gpu 1'
+ . path.sh
[0m
[91m+++ pwd
[0m
[91m++ export KALDI_ROOT=/usr/local/kaldi/egs/taiwanese/s5c/../../..
++ KALDI_ROOT=/usr/local/kaldi/egs/taiwanese/s5c/../../..
++ export PATH=/usr/local/kaldi/egs/taiwanese/s5c/utils/:/usr/local/kaldi/egs/taiwanese/s5c/../../../tools/openfst/bin:/usr/local/kaldi/egs/taiwanese/s5c:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ PATH=/usr/local/kaldi/egs/taiwanese/s5c/utils/:/usr/local/kaldi/egs/taiwanese/s5c/../../../tools/openfst/bin:/usr/local/kaldi/egs/taiwanese/s5c:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ '[' '!' -f /usr/local/kaldi/egs/taiwanese/s5c/../../../tools/config/common_path.sh ']'
++ . /usr/local/kaldi/egs/taiwanese/s5c/../../../tools/config/common_path.sh
+++ '[' -z /usr/local/kaldi/egs/taiwanese/s5c/../../.. ']'
+++ export PATH=/usr/local/kaldi/egs/taiwanese/s5c/../../../src/bin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/chainbin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/featbin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/fgmmbin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/fstbin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/gmmbin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/ivectorbin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/kwsbin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/latbin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/lmbin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/nnet2bin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/nnet3bin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/nnetbin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/online2bin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/onlinebin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/sgmm2bin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/sgmmbin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/tfrnnlmbin:/usr/local/kaldi/egs/taiwanese/s5c/utils/:/usr/local/kaldi/egs/taiwanese/s5c/../../../tools/openfst/bin:/usr/local/kaldi/egs/taiwanese/s5c:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+++ PATH=/usr/local/kaldi/egs/taiwanese/s5c/../../../src/bin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/chainbin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/featbin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/fgmmbin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/fstbin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/gmmbin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/ivectorbin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/kwsbin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/latbin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/lmbin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/nnet2bin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/nnet3bin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/nnetbin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/online2bin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/onlinebin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/sgmm2bin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/sgmmbin:/usr/local/kaldi/egs/taiwanese/s5c/../../../src/tfrnnlmbin:/usr/local/kaldi/egs/taiwanese/s5c/utils/:/usr/local/kaldi/egs/taiwanese/s5c/../../../tools/openfst/bin:/usr/local/kaldi/egs/taiwanese/s5c:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ export LC_ALL=C
++ LC_ALL=C
+ set -e
+ STAGE=0
+ nj=4
+ lang=data/lang_free
+ '[' 0 -le 6 ']'
+ utils/utt2spk_to_spk2utt.pl data/dev/utt2spk
[0m
[91m+ for i in dev
+ data_dir=data/dev
[0m
[91m+ make_mfcc_log=data/mfcc_log/dev
+ mfccdir=data/mfcc/dev
+ rm -rf data/mfcc_log/dev data/mfcc/dev
[0m
[91m+ mkdir -p data/mfcc_log/dev data/mfcc/dev
[0m
[91m+ utils/fix_data_dir.sh data/dev
[0m
utils/fix_data_dir.sh: file data/dev/utt2spk is not in sorted order or not unique, sorting it

utils/fix_data_dir.sh: file data/dev/text is not in sorted order or not unique, sorting it

utils/fix_data_dir.sh: file data/dev/segments is not in sorted order or not unique, sorting it

fix_data_dir.sh: kept all 10350 utterances.

fix_data_dir.sh: old files are kept in data/dev/.backup

[91m+ steps/make_mfcc.sh --nj 4 --cmd run.pl data/dev data/mfcc_log/dev data/mfcc/dev
[0m
steps/make_mfcc.sh --nj 4 --cmd run.pl data/dev data/mfcc_log/dev data/mfcc/dev

Checking data/dev/text ...
--> reading data/dev/text
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces

utils/validate_data_dir.sh: Successfully validated data-directory data/dev

steps/make_mfcc.sh [info]: segments file exists: using that.

Succeeded creating MFCC features for dev

[91m+ steps/compute_cmvn_stats.sh data/dev data/mfcc_log/dev data/mfcc/dev
[0m
steps/compute_cmvn_stats.sh data/dev data/mfcc_log/dev data/mfcc/dev

Succeeded creating CMVN stats for dev

[91m+ '[' 0 -le 10 ']'
[0m
[91m+ graph_dir=exp/tri1/graph
+ run.pl exp/tri1/graph/mkgraph.log utils/mkgraph.sh data/lang_free exp/tri1 exp/tri1/graph
[0m
[91m+ steps/decode_si.sh --nj 4 --cmd 'run.pl --mem 4G' --config conf/decode.config exp/tri1/graph data/dev exp/tri1/decode_train_dev
[0m
steps/decode_si.sh --nj 4 --cmd run.pl --mem 4G --config conf/decode.config exp/tri1/graph data/dev exp/tri1/decode_train_dev

[91mfilter_scps.pl: warning: some input lines were output to multiple files [OK if splitting per utt] 
[0m
[91mfilter_scps.pl: warning: some input lines were output to multiple files [OK if splitting per utt] 
[0m
decode.sh: feature type is delta

...
```

**Comment by leo424y** [comment]
OK，原來是要兩天！

**Comment by leo424y** [comment]
2d 10 hrs 結果如
```
Step 49/49 : RUN bash -c 'time bash 看結果.sh'

 ---\> Running in 8a0ff5129891

exp/tri1/decode\_train\_dev:

%WER 27.65 \[ 24118 / 87227, 2270 ins, 4201 del, 17647 sub \] 

exp/tri2/decode\_train\_dev:

%WER 27.26 \[ 23776 / 87227, 2060 ins, 4251 del, 17465 sub \] 

exp/tri3/decode\_train\_dev:

%WER 24.54 \[ 21404 / 87227, 1995 ins, 3893 del, 15516 sub \] 

exp/tri4/decode\_train\_dev:

%WER 24.42 \[ 21302 / 87227, 1871 ins, 3889 del, 15542 sub \] 

exp/tri4/decode\_train\_dev.si:

%WER 34.14 \[ 29783 / 87227, 2453 ins, 4850 del, 22480 sub \] 

\[91m
real	0m0.059s
user	0m0.000s
sys	0m0.012s
\[0m
 ---\> c6c35ed89184

Removing intermediate container 8a0ff5129891

Successfully built c6c35ed89184

Docker Build Response : c6c35ed89184
Docker Build Done
Finished: SUCCESS
```

**Comment by sih4sing5hong5** [comment]
成功嘍，我這幾工共語言模型的script整理好，予你處理

**Comment by leo424y** [comment]
噢耶！成功，接下來語言模型，再勞煩您了
