### ISSUE TITLE
free-syllable-tw01test-知影8个語者 的實驗

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/siann1-hak8_boo5-hing5#42]
`free-syllable-tw01test-知影8个語者`
https://github.com/twgo/gi2-gian5_boo5-hing5/tree/free-syllable-tw01test-%E7%9F%A5%E5%BD%B18%E4%B8%AA%E8%AA%9E%E8%80%85

**Comment by leo424y** [comment]
Step 10/17 : RUN python3 manage.py 匯出Kaldi格式資料 --資料夾 tshi3 臺語 $KALDI_S5C


 ---> Running in dfe33ac9121f

[91m綜合標音deprecated，0.7版會提掉
綜合標音deprecated，0.7版會提掉
綜合標音deprecated，0.7版會提掉
usage: manage.py 匯出Kaldi格式資料 [-h] [--version] [-v {0,1,2,3}]
                             [--settings SETTINGS] [--pythonpath PYTHONPATH]
                             [--traceback] [--no-color] [--語言文本 語言文本]
                             [--連紲詞長度 連紲詞長度] [--資料夾 資料夾名]
                             語言 辭典輸出函式 匯出路徑
manage.py 匯出Kaldi格式資料: error: the following arguments are required: 匯出路徑
[0m
ERROR: Build step failed with exception
com.github.dockerjava.api.exception.DockerClientException: Could not build image: The command '/bin/sh -c python3 manage.py 匯出Kaldi格式資料 --資料夾 tshi3 臺語 $KALDI_S5C' returned a non-zero code: 2
	at com.github.dockerjava.core.command.BuildImageResultCallback.getImageId(BuildImageResultCallback.java:79)
	at com.github.dockerjava.core.command.BuildImageResultCallback.awaitImageId(BuildImageResultCallback.java:51)
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run.buildImage(DockerBuilderPublisher.java:349)
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run.run(DockerBuilderPublisher.java:283)
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher.perform(DockerBuilderPublisher.java:426)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1724)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429) 

https://jenkins.iis.sinica.edu.tw/job/gi2-gian5_boo5-hing5/78/console 直接接  
https://jenkins.iis.sinica.edu.tw/job/siann1-hak8_boo5-hing5/88 噴錯

請問有特定適用的branch嗎？

**Comment by sih4sing5hong5** [comment]
我有的所在無改著，你kah仝語者比一个
```
git diff free-syllable-tw01test-仝語者 
```

**Comment by leo424y** [comment]
``` 
< RUN python3 manage.py 匯入TW01Test /usr/local/pian7sik4_gi2liau7/TW01TestAll
---
> RUN echo 匯入TW01Test當作仝語者
> RUN pip3 install --upgrade tw01
> RUN python3 manage.py 匯入TW01Test當作仝語者 /usr/local/pian7sik4_gi2liau7/TW01TestAll
18c20
< RUN python3 manage.py 匯出Kaldi格式資料 --資料夾 tshi3 臺語 $KALDI_S5C
---
> RUN python3 manage.py 匯出Kaldi格式資料 --資料夾 tshi3 臺語 拆做聲韻 $KALDI_S5C
```

 看起來只需加    拆做聲韻   已改並重跑

**Comment by sih4sing5hong5** [comment]
應該是按呢

**Comment by sih4sing5hong5** [comment]
若有時間，走對應的全部branch喲

tw01
tw01+tw02
twisas
...

**Comment by sih4sing5hong5** [comment]
看你有準備報告--ah
